### ISSUE TITLE
v0.6.0 not working on heroku

### ISSUE THREAD

**Issue by imanel** [fb55/readabilitySAX#3]
If I try to deploy on [heroku](http://heroku.com) I will get following error:

```
2011-12-02T13:43:47+00:00 heroku[web.1]: State changed from created to starting
2011-12-02T13:43:49+00:00 heroku[web.1]: Starting process with command `node web.js`
2011-12-02T13:43:49+00:00 app[web.1]: 
2011-12-02T13:43:49+00:00 app[web.1]: node.js:134
2011-12-02T13:43:49+00:00 app[web.1]:         throw e; // process.nextTick error, or 'error' event on first tick
2011-12-02T13:43:49+00:00 app[web.1]:         ^
2011-12-02T13:43:49+00:00 app[web.1]: Error: Cannot find module '../ReadabilitySAX'
2011-12-02T13:43:49+00:00 app[web.1]:     at Function._resolveFilename (module.js:320:11)
2011-12-02T13:43:49+00:00 app[web.1]:     at Function._load (module.js:266:25)
2011-12-02T13:43:49+00:00 app[web.1]:     at require (module.js:348:19)
2011-12-02T13:43:49+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/readabilitySAX/node/index.js:1:81)
2011-12-02T13:43:49+00:00 app[web.1]:     at Module._compile (module.js:404:26)
2011-12-02T13:43:49+00:00 app[web.1]:     at Object..js (module.js:410:10)
2011-12-02T13:43:49+00:00 app[web.1]:     at Module.load (module.js:336:31)
2011-12-02T13:43:49+00:00 app[web.1]:     at Function._load (module.js:297:12)
2011-12-02T13:43:49+00:00 app[web.1]:     at require (module.js:348:19)
2011-12-02T13:43:49+00:00 app[web.1]:     at Object.<anonymous> (/app/web.js:1:82)
2011-12-02T13:43:49+00:00 heroku[web.1]: Process exited
2011-12-02T13:43:50+00:00 heroku[web.1]: State changed from starting to crashed
```

web.js is small wrapper around readabilitySAX. Everything is working on my local machine(node v0.4.7, npm v1.0.94) but on heroku(the same version of node and npm) it's failing.

my package.json:

```
{
  "name": "myapp",
  "version": "0.0.1",
  "dependencies": {
    "readabilitySAX": "0.6.0"
  }
}
```
